In [1]:
import numpy as np

In [2]:
entradas = np.array([[0,0], [0,1], [1,0], [1,1]])
saidas = np.array([0,0,0,1])
pesos = np.array([0.0, 0.0])
taxaAprendizagem = 0.1

In [3]:
def stepFunction(soma):
    if (soma >= 1):
        return 1
    return 0

In [4]:
def calculaSaida(registro):
    s = registro.dot(pesos)
    return stepFunction(s)

In [5]:
def treinar():
    erroTotal = 1
    while (erroTotal != 0):
        erroTotal = 0
        for i in range(len(saidas)):
            saidaCalculada = calculaSaida(np.asarray(entradas[i]))
            erro = abs(saidas[i] - saidaCalculada)
            erroTotal += erro
            for j in range(len(pesos)):
                pesos[j] = pesos[j] + (taxaAprendizagem * entradas[i][j] * erro)
                print('Peso atualizado: ' + str(pesos[j]))
        print('Total de erros: ' + str(erroTotal))
                

In [6]:
treinar()

Peso atualizado: 0.0
Peso atualizado: 0.0
Peso atualizado: 0.0
Peso atualizado: 0.0
Peso atualizado: 0.0
Peso atualizado: 0.0
Peso atualizado: 0.1
Peso atualizado: 0.1
Total de erros: 1
Peso atualizado: 0.1
Peso atualizado: 0.1
Peso atualizado: 0.1
Peso atualizado: 0.1
Peso atualizado: 0.1
Peso atualizado: 0.1
Peso atualizado: 0.2
Peso atualizado: 0.2
Total de erros: 1
Peso atualizado: 0.2
Peso atualizado: 0.2
Peso atualizado: 0.2
Peso atualizado: 0.2
Peso atualizado: 0.2
Peso atualizado: 0.2
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.30000000000000004
Total de erros: 1
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.30000000000000004
Peso atualizado: 0.4
Peso atualizado: 0.4
Total de erros: 1
Peso atualizado: 0.4
Peso atualizado: 0.4
Peso atualizado: 0.4
Peso atualizado: 0.4
Peso atualizado: 0.4
Peso atualizado: 0.4
Pe

# ATUALIZA O PESO - PESO(N+1) = PESO(N) + (TAXAAPRENDIZAGEM * ENTRADA * ERRO)

In [8]:
print('rede neural treinada')
print(calculaSaida(entradas[0]))
print(calculaSaida(entradas[1]))
print(calculaSaida(entradas[2]))
print(calculaSaida(entradas[3]))

rede neural treinada
0
0
0
1


In [19]:
def sigmoid(soma):
    return 1 / (1 + np.exp(- soma))

In [21]:
entradas = np.array([[0,0],
                     [0,1],
                     [1,0],
                     [1,1]])

In [23]:
saidas = np.array([[0],[1],[1],[0]])

In [27]:
pesos0 = np.array([[-0.424, -0.740, -0.961],
                   [0.358, -0.893, -0.148]])

In [29]:
peso1 = np.array([[-0.017], [-0.893], [0.148]])

In [31]:
epocas = 100
for j in range(epocas):
    camadaEntrada = entradas
    somaSinapse0 = np.dot(camadaEntrada, pesos0)
    camadaOculta = sigmoid(somaSinapse0)

    somaSinapse1 = np.dot(camadaOculta, peso1)
    camadaSaida = sigmoid(somaSinapse1)

In [33]:
print(camadaOculta)

[[0.5        0.5        0.5       ]
 [0.5885562  0.29049112 0.46306739]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.16341981 0.24805737]]


Digite sua idade 25


censura: Apenas maiores de 18 anos
